-- AlterEnum (item 17 release 2026-05)
ALTER TYPE "NotificaTipo" ADD VALUE 'N14_ACCOUNT_SOSPESO';
ALTER TYPE "NotificaTipo" ADD VALUE 'N15_ACCOUNT_RIATTIVATO';
ALTER TYPE "NotificaTipo" ADD VALUE 'N16_ACCOUNT_ELIMINATO';
